# Generated by Django 4.0.3 on 2022-05-20 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_restraunt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restraunt',
            new_name='Restaurant',
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.IntegerField()),
                ('product_image', models.CharField(max_length=70)),
                ('Restraunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant')),
            ],
        ),
    ]
