# Generated by Django 4.0.3 on 2022-05-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_rename_restraunt_restaurant_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(default='Order now', max_length=500),
        ),
    ]
