# Generated by Django 4.0.3 on 2022-05-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_products_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Restraunt',
            new_name='Restaurant',
        ),
    ]
