# Generated by Django 4.0.3 on 2022-05-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_rename_restraunt_products_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Restaurant',
            new_name='Restaurant_name',
        ),
    ]
