# Generated by Django 4.0.3 on 2022-05-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_rename_restaurant_products_restaurant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Restaurant_name',
            new_name='RestaurantName',
        ),
    ]
