# Generated by Django 4.0.3 on 2022-05-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_rename_restaurant_name_products_restaurantname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='RestaurantName',
            new_name='Restaurant_name',
        ),
    ]
